image: Visual Studio 2019

environment:
  matrix:
  - Architecture: arm64

install:
- cmd: git submodule update --init --recursive
- ps: ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\"

build: off
build_script:
- ps: >-
    .\build.ps1

test: off
test_script:
- ps: Get-ChildItem dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
